-- AViD block stub
-- label: def:base-generadora
-- type:  definition
-- title:
-- See ../TASK.md for the informal statement and proof.
--
-- Write the formalized Lean declaration(s) below this line.

import Papers.AyrtonPortoTesis.Paper

/-- A family `B` of subsets of `X` is a base (basis) for a topology on `X` if:
    (1) the union of all sets in `B` covers `X`;
    (2) for any `B1, B2 in B` and `x in B1 cap B2`, there exists `B3 in B`
        with `x in B3 subseteq B1 cap B2`.
    The topology generated by `B` is the family of all arbitrary unions of elements of `B`. -/
structure def_base_generadora (X : Type*) where
  /-- The base family: a collection of subsets of X. -/
  B : Set (Set X)
  /-- Condition 1: B covers X (the union of all sets in B equals X). -/
  covers : Set.sUnion B = Set.univ
  /-- Condition 2: for any B1, B2 in B and x in B1 cap B2, there exists B3 in B
      with x in B3 subseteq B1 cap B2. -/
  inter_refine : forall (B1 B2 : Set X), B B1 -> B B2 ->
    forall (x : X), B1 x /\ B2 x ->
    exists B3 : Set X, B B3 /\ B3 x /\ Set.Subset B3 (Set.inter B1 B2)

/-- The topology generated by a base: the family of all arbitrary unions
    of elements of the base. -/
def def_base_generadora.topologia_generada {X : Type*} (base : def_base_generadora X) :
    Set (Set X) :=
  fun U => exists F : Set (Set X), (forall V, F V -> base.B V) /\ U = Set.sUnion F
