-- AViD block stub
-- label: def:subbase
-- type:  definition
-- title:
-- See ../TASK.md for the informal statement and proof.
--
-- Write the formalized Lean declaration(s) below this line.

import Papers.AyrtonPortoTesis.Paper

/-- A subbase for a topology on X is a family S of subsets of X such that
    the union of all members of S covers X (i.e. sUnion S = univ).
    The topology generated by S consists of all sets U such that for every
    x in U there exist finitely many S1, ..., Sn in S satisfying
    x in S1 inter ... inter Sn subseteq U. -/
structure def_subbase (X : Type*) where
  /-- The subbase family: a collection of subsets of X. -/
  S : Set (Set X)
  /-- Covering condition: the union of all members of S equals X. -/
  covers : Set.sUnion S = Set.univ

/-- The topology generated by a subbase sub: the family of all sets U such that
    for every x in U there exists a finite subfamily F of sub.S with
    x in sInter F subseteq U. -/
def def_subbase.topologia_generada {X : Type*} (sub : def_subbase X) : Set (Set X) :=
  fun U => forall x : X, U x ->
    exists F : Finset (Set X),
      (forall V, (F : Set (Set X)) V -> sub.S V) /\
      Set.sInter (F : Set (Set X)) x /\
      Set.Subset (Set.sInter (F : Set (Set X))) U
